In [1]:
# ===============================
# 1. Libraries
# ===============================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_regression

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor


from sklearn.metrics import r2_score

In [2]:
# ===============================
# 2. Load Dataset
# ===============================
data = pd.read_csv("FD001_combined.csv")

# basic checks
print(data.isnull().sum())

unit_number       0
time_in_cycles    0
OS1               0
OS2               0
OS3               0
sensor_1          0
sensor_2          0
sensor_3          0
sensor_4          0
sensor_5          0
sensor_6          0
sensor_7          0
sensor_8          0
sensor_9          0
sensor_10         0
sensor_11         0
sensor_12         0
sensor_13         0
sensor_14         0
sensor_15         0
sensor_16         0
sensor_17         0
sensor_18         0
sensor_19         0
sensor_20         0
sensor_21         0
RUL               0
dtype: int64

In [3]:
data.isnull().sum()

unit_number       0
time_in_cycles    0
OS1               0
OS2               0
OS3               0
sensor_1          0
sensor_2          0
sensor_3          0
sensor_4          0
sensor_5          0
sensor_6          0
sensor_7          0
sensor_8          0
sensor_9          0
sensor_10         0
sensor_11         0
sensor_12         0
sensor_13         0
sensor_14         0
sensor_15         0
sensor_16         0
sensor_17         0
sensor_18         0
sensor_19         0
sensor_20         0
sensor_21         0
RUL               0
dtype: int64

In [4]:
#=====================
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33727 entries, 0 to 33726
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   unit_number     33727 non-null  int64
 1   time_in_cycles  33727 non-null  int64
 2   OS1             33727 non-null  float64
 3   OS2             33727 non-null  float64
 4   OS3             33727 non-null  float64
 5   sensor_1        33727 non-null  float64
 6   sensor_2        33727 non-null  float64
 7   sensor_3        33727 non-null  float64
 8   sensor_4        33727 non-null  float64
 9   sensor_5        33727 non-null  float64
 10  sensor_6        33727 non-null  float64
 11  sensor_7        33727 non-null  float64
 12  sensor_8        33727 non-null  float64
 13  sensor_9        33727 non-null  float64
 14  sensor_10       33727 non-null  float64
 15  sensor_11       33727 non-null  float64
 16  sensor_12       33727 non-null  float64
 17  sensor_13       33727 non-null  float64
 18  sensor_14       33727 non-null  float64
 19  sensor_15       33727 non-null  float64
 20  sensor_16       33727 non-null  float64
 21  sensor_17       33727 non-null  int64
 22  sensor_18       33727 non-null  int64
 23  sensor_19       33727 non-null  float64
 24  sensor_20       33727 non-null  float64
 25  sensor_21       33727 non-null  float64
 26  RUL             33727 non-null  int64
dtypes: float64(22), int64(5)
memory usage: 6.9 MB

In [5]:
data.head()

,unit_number,time_in_cycles,OS1,OS2,OS3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,191
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,190
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,189
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,188
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,187

In [6]:
data.tail()

,unit_number,time_in_cycles,OS1,OS2,OS3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
33722,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,24
33723,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,23
33724,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,22
33725,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,21
33726,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,20

In [7]:
data.describe()

,unit_number,time_in_cycles,OS1,OS2,OS3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
count,33727.000000,33727.000000,33727.000000,33727.000000,33727.0,3.372700e+04,33727.000000,33727.000000,33727.000000,3.372700e+04,...,33727.000000,33727.000000,33727.000000,3.372700e+04,33727.000000,33727.0,33727.0,33727.000000,33727.000000,33727.000000
mean,51.521066,96.393572,-0.000010,0.000003,100.0,5.186700e+02,642.601005,1589.581927,1407.303559,1.462000e+01,...,2388.086395,8141.887005,8.435816,3.000000e-02,392.962523,2388.0,100.0,38.845871,23.307581,120.788775
std,28.866537,65.100528,0.002193,0.000293,0.0,7.276065e-12,0.474789,5.840324,8.432656,3.884950e-12,...,0.067620,16.382482,0.035360,2.011268e-14,1.468023,0.0,0.0,0.170757,0.102073,67.218901
min,1.000000,1.000000,-0.008700,-0.000600,100.0,5.186700e+02,641.130000,1569.040000,1382.250000,1.462000e+01,...,2387.880000,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200,0.000000
25%,27.000000,43.000000,-0.001500,-0.000200,100.0,5.186700e+02,642.270000,1585.530000,1401.230000,1.462000e+01,...,2388.040000,8132.780000,8.411000,3.000000e-02,392.000000,2388.0,100.0,38.740000,23.245900,68.000000
50%,52.000000,88.000000,0.000000,0.000000,100.0,5.186700e+02,642.560000,1589.210000,1406.450000,1.462000e+01,...,2388.080000,8139.620000,8.432400,3.000000e-02,393.000000,2388.0,100.0,38.860000,23.316600,121.000000
75%,77.000000,140.000000,0.001500,0.000300,100.0,5.186700e+02,642.890000,1593.160000,1412.240000,1.462000e+01,...,2388.130000,8146.600000,8.457000,3.000000e-02,394.000000,2388.0,100.0,38.970000,23.379200,167.000000
max,100.000000,362.000000,0.008700,0.000700,100.0,5.186700e+02,644.530000,1616.910000,1441.490000,1.462000e+01,...,2388.560000,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.641900,361.000000

In [8]:
import pandas as pd

central = pd.DataFrame(index=['mean', 'median', 'mode', 'Q1:25%', 'Q2:50%', 'Q3:75%', 'Q4:100%','IQR','1.5Rule','Lesser','Greater','min','max'], columns=data.columns)

desc = data.describe()  # compute once

for col in data.columns:
    central.loc['mean', col]   = data[col].mean()
    central.loc['median', col] = data[col].median()
    central.loc['mode', col]   = data[col].mode()[0] 
    central.loc['Q1:25%', col] = desc[col]['25%']
    central.loc['Q2:50%', col]  = desc[col]['50%']
    central.loc['Q3:75%', col]  = desc[col]['75%']
    central.loc['Q4:100%', col]  = desc[col]['max']
    central.loc['IQR', col]   = central.loc['Q3:75%', col] - central.loc['Q1:25%', col] 
    central.loc['1.5Rule', col]=1.5*central.loc['IQR', col]
    central.loc['Lesser', col]=central.loc['Q1:25%', col]-central.loc['1.5Rule', col]
    central.loc['Greater', col]=central.loc['Q3:75%', col]+central.loc['1.5Rule', col]
    central.loc['min', col]=data[col].min()
    central.loc['max', col]=data[col].max()
    

central

,unit_number,time_in_cycles,OS1,OS2,OS3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
mean,51.521066,96.393572,-0.00001,0.000003,100.0,518.67,642.601005,1589.581927,1407.303559,14.62,...,2388.086395,8141.887005,8.435816,0.03,392.962523,2388.0,100.0,38.845871,23.307581,120.788775
median,52.0,88.0,-0.0,-0.0,100.0,518.67,642.56,1589.21,1406.45,14.62,...,2388.08,8139.62,8.4324,0.03,393.0,2388.0,100.0,38.86,23.3166,121.0
mode,49,1,0.0,-0.0003,100.0,518.67,642.49,1589.76,1401.27,14.62,...,2388.07,8138.31,8.4309,0.03,393,2388,100.0,38.89,23.3222,137
Q1:25%,27.0,43.0,-0.0015,-0.0002,100.0,518.67,642.27,1585.53,1401.23,14.62,...,2388.04,8132.78,8.411,0.03,392.0,2388.0,100.0,38.74,23.2459,68.0
Q2:50%,52.0,88.0,0.0,0.0,100.0,518.67,642.56,1589.21,1406.45,14.62,...,2388.08,8139.62,8.4324,0.03,393.0,2388.0,100.0,38.86,23.3166,121.0
Q3:75%,77.0,140.0,0.0015,0.0003,100.0,518.67,642.89,1593.16,1412.24,14.62,...,2388.13,8146.6,8.457,0.03,394.0,2388.0,100.0,38.97,23.3792,167.0
Q4:100%,100.0,362.0,0.0087,0.0007,100.0,518.67,644.53,1616.91,1441.49,14.62,...,2388.56,8293.72,8.5848,0.03,400.0,2388.0,100.0,39.43,23.6419,361.0
IQR,50.0,97.0,0.003,0.0005,0.0,0.0,0.62,7.63,11.01,0.0,...,0.09,13.82,0.046,0.0,2.0,0.0,0.0,0.23,0.1333,99.0
1.5Rule,75.0,145.5,0.0045,0.00075,0.0,0.0,0.93,11.445,16.515,0.0,...,0.135,20.73,0.069,0.0,3.0,0.0,0.0,0.345,0.19995,148.5
Lesser,-48.0,-102.5,-0.006,-0.00095,100.0,518.67,641.34,1574.085,1384.715,14.62,...,2387.905,8112.05,8.342,0.03,389.0,2388.0,100.0,38.395,23.04595,-80.5
Greater,152.0,285.5,0.006,0.00105,100.0,518.67,643.82,1604.605,1428.755,14.62,...,2388.265,8167.33,8.526,0.03,397.0,2388.0,100.0,39.315,23.57915,315.5
min,1,1,-0.0087,-0.0006,100.0,518.67,641.13,1569.04,1382.25,14.62,...,2387.88,8099.94,8.3249,0.03,388,2388,100.0,38.14,22.8942,0
max,100,362,0.0087,0.0007,100.0,518.67,644.53,1616.91,1441.49,14.62,...,2388.56,8293.72,8.5848,0.03,400,2388,100.0,39.43,23.6419,361

In [9]:
## Finding outlers 

lesser = []
greater = []

for col in data.columns:
    if central.loc['min', col] < central.loc['Lesser', col]:
        lesser.append(col)

    if central.loc['max', col] > central.loc['Greater', col]:
        greater.append(col)

In [10]:
lesser

['OS1',
 'sensor_2',
 'sensor_3',
 'sensor_4',
 'sensor_6',
 'sensor_7',
 'sensor_8',
 'sensor_9',
 'sensor_11',
 'sensor_12',
 'sensor_13',
 'sensor_14',
 'sensor_15',
 'sensor_17',
 'sensor_20',
 'sensor_21']

In [11]:
greater

['time_in_cycles',
 'OS1',
 'sensor_2',
 'sensor_3',
 'sensor_4',
 'sensor_7',
 'sensor_8',
 'sensor_9',
 'sensor_11',
 'sensor_12',
 'sensor_13',
 'sensor_14',
 'sensor_15',
 'sensor_17',
 'sensor_20',
 'sensor_21',
 'RUL']

In [12]:
### Replacing outliers

In [13]:
for col in lesser:
    data.loc[data[col] < central.loc['Lesser', col], col] = central.loc['Lesser', col]
    #data[OS1(col name)] < central.loc['Lesser', col] lesser value from central taple (0.006)
    #2<10--> true
    #12<10--> False
    #[True, False]-- Row condition
    # data.loc[ ROW condition , COLUMN ]
    #data.loc[[True, False], "marks"]

for col in greater:
    data.loc[data[col] > central.loc['Greater', col], col] = central.loc['Greater', col]

C:\Users\anand\AppData\Local\Temp\ipykernel_10156\1375815358.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '285.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data[col] > central.loc['Greater', col], col] = central.loc['Greater', col]
C:\Users\anand\AppData\Local\Temp\ipykernel_10156\1375815358.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '315.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data[col] > central.loc['Greater', col], col] = central.loc['Greater', col]

In [14]:
import pandas as pd

central = pd.DataFrame(index=['mean', 'median', 'mode', 'Q1:25%', 'Q2:50%', 'Q3:75%', 'Q4:100%','IQR','1.5Rule','Lesser','Greater','min','max', 'kurtosis', 'skew'
                             ,'Variance', 'standard deviation'], columns=data.columns)

desc = data.describe()  # compute once

for col in data.columns:
    central.loc['mean', col]   = data[col].mean()
    central.loc['median', col] = data[col].median()
    central.loc['mode', col]   = data[col].mode()[0] 
    central.loc['Q1:25%', col] = desc[col]['25%']
    central.loc['Q2:50%', col]  = desc[col]['50%']
    central.loc['Q3:75%', col]  = desc[col]['75%']
    central.loc['Q4:100%', col]  = desc[col]['max']
    central.loc['IQR', col]   = central.loc['Q3:75%', col] - central.loc['Q1:25%', col] 
    central.loc['1.5Rule', col]=1.5*central.loc['IQR', col]
    central.loc['Lesser', col]=central.loc['Q1:25%', col]-central.loc['1.5Rule', col]
    central.loc['Greater', col]=central.loc['Q3:75%', col]+central.loc['1.5Rule', col]
    central.loc['min', col]=data[col].min()
    central.loc['max', col]=data[col].max()
    central.loc['kurtosis', col]=data[col].kurtosis()
    central.loc['skew', col]=data[col].skew()
    central.loc['Variance', col]=data[col].var()
    central.loc['standard deviation', col]=data[col].std()
    
    

central

,unit_number,time_in_cycles,OS1,OS2,OS3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
mean,51.521066,96.20319,-0.00001,0.000003,100.0,518.67,642.599244,1589.560443,1407.261051,14.62,...,2388.086006,8140.513949,8.435666,0.03,392.959913,2388.0,100.0,38.846434,23.307996,120.72949
median,52.0,88.0,-0.0,-0.0,100.0,518.67,642.56,1589.21,1406.45,14.62,...,2388.08,8139.62,8.4324,0.03,393.0,2388.0,100.0,38.86,23.3166,121.0
mode,49,285.5,0.0,-0.0003,100.0,518.67,643.82,1604.605,1428.755,14.62,...,2388.07,8167.33,8.526,0.03,393,2388,100.0,38.89,23.04595,137.0
Q1:25%,27.0,43.0,-0.0015,-0.0002,100.0,518.67,642.27,1585.53,1401.23,14.62,...,2388.04,8132.78,8.411,0.03,392.0,2388.0,100.0,38.74,23.2459,68.0
Q2:50%,52.0,88.0,0.0,0.0,100.0,518.67,642.56,1589.21,1406.45,14.62,...,2388.08,8139.62,8.4324,0.03,393.0,2388.0,100.0,38.86,23.3166,121.0
Q3:75%,77.0,140.0,0.0015,0.0003,100.0,518.67,642.89,1593.16,1412.24,14.62,...,2388.13,8146.6,8.457,0.03,394.0,2388.0,100.0,38.97,23.3792,167.0
Q4:100%,100.0,285.5,0.006,0.0007,100.0,518.67,643.82,1604.605,1428.755,14.62,...,2388.265,8167.33,8.526,0.03,397.0,2388.0,100.0,39.315,23.57915,315.5
IQR,50.0,97.0,0.003,0.0005,0.0,0.0,0.62,7.63,11.01,0.0,...,0.09,13.82,0.046,0.0,2.0,0.0,0.0,0.23,0.1333,99.0
1.5Rule,75.0,145.5,0.0045,0.00075,0.0,0.0,0.93,11.445,16.515,0.0,...,0.135,20.73,0.069,0.0,3.0,0.0,0.0,0.345,0.19995,148.5
Lesser,-48.0,-102.5,-0.006,-0.00095,100.0,518.67,641.34,1574.085,1384.715,14.62,...,2387.905,8112.05,8.342,0.03,389.0,2388.0,100.0,38.395,23.04595,-80.5
Greater,152.0,285.5,0.006,0.00105,100.0,518.67,643.82,1604.605,1428.755,14.62,...,2388.265,8167.33,8.526,0.03,397.0,2388.0,100.0,39.315,23.57915,315.5
min,1,1.0,-0.006,-0.0006,100.0,518.67,641.34,1574.085,1384.715,14.62,...,2387.905,8112.05,8.342,0.03,389,2388,100.0,38.395,23.04595,0.0
max,100,285.5,0.006,0.0007,100.0,518.67,643.82,1604.605,1428.755,14.62,...,2388.265,8167.33,8.526,0.03,397,2388,100.0,39.315,23.57915,315.5
kurtosis,-1.200587,-0.219579,-0.139461,-1.130808,0.0,0.0,-0.129114,-0.08218,-0.082925,0.0,...,-0.079997,0.17804,-0.086679,0.0,0.033669,0.0,0.0,-0.063977,-0.091917,-0.385248
skew,-0.04248,0.601457,-0.012894,0.011956,0.0,0.0,0.326653,0.289675,0.484662,0.0,...,0.380459,0.480051,0.408088,0.0,0.383214,0.0,0.0,-0.380063,-0.373494,0.273349
Variance,833.276961,4158.19749,0.000005,0.0,0.0,0.0,0.220413,33.283962,69.07937,0.0,...,0.004404,132.738671,0.001219,0.0,2.130279,0.0,0.0,0.028557,0.010166,4493.91319
standard deviation,28.866537,64.484087,0.002182,0.000293,0.0,0.0,0.469482,5.769225,8.3114,0.0,...,0.066363,11.521227,0.034914,0.0,1.459548,0.0,0.0,0.168987,0.100827,67.036656

In [15]:
lesser = []
greater = []

for col in data.columns:
    if central.loc['min', col] < central.loc['Lesser', col]:
        lesser.append(col)

    if central.loc['max', col] > central.loc['Greater', col]:
        greater.append(col)

In [16]:
lesser # here no lesser outliers we have replaced it

[]

In [17]:
greater

[]

## Bivariate analysis

In [18]:
### covariance

pd.options.display.float_format = '{:.4f}'.format
cov_matrix = data.cov()
cov_matrix

,unit_number,time_in_cycles,OS1,OS2,OS3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
unit_number,833.2770,110.9691,-0.0011,-0.0000,0.0000,0.0000,0.4513,4.8702,11.0744,0.0000,...,0.1086,-8.4912,0.0415,0.0000,1.5028,0.0000,0.0000,-0.2061,-0.1071,79.9170
time_in_cycles,110.9691,4158.1975,-0.0006,0.0000,0.0000,0.0000,15.6681,187.6910,319.8202,-0.0000,...,1.9429,247.1554,1.2544,-0.0000,50.2675,0.0000,0.0000,-6.0215,-3.5920,-3155.1332
OS1,-0.0011,-0.0006,0.0000,0.0000,0.0000,0.0000,0.0000,-0.0000,0.0001,-0.0000,...,0.0000,-0.0002,0.0000,-0.0000,0.0000,0.0000,0.0000,-0.0000,-0.0000,-0.0006
OS2,-0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,-0.0000,0.0000,0.0000,-0.0000,...,-0.0000,-0.0000,0.0000,-0.0000,0.0000,0.0000,0.0000,-0.0000,0.0000,-0.0000
OS3,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
sensor_1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
sensor_2,0.4513,15.6681,0.0000,-0.0000,0.0000,0.0000,0.2204,1.5086,2.6613,-0.0000,...,0.0198,0.1703,0.0105,-0.0000,0.4029,0.0000,0.0000,-0.0496,-0.0297,-17.6097
sensor_3,4.8702,187.6910,-0.0000,0.0000,0.0000,0.0000,1.5086,33.2840,30.4613,-0.0000,...,0.2194,5.5751,0.1200,-0.0000,4.6578,0.0000,0.0000,-0.5670,-0.3413,-206.5406
sensor_4,11.0744,319.8202,0.0001,0.0000,0.0000,0.0000,2.6613,30.4613,69.0794,-0.0000,...,0.3998,2.8248,0.2109,-0.0000,8.1129,0.0000,0.0000,-1.0053,-0.5952,-355.0099
sensor_5,0.0000,-0.0000,-0.0000,-0.0000,0.0000,0.0000,-0.0000,-0.0000,-0.0000,0.0000,...,-0.0000,0.0000,0.0000,0.0000,-0.0000,0.0000,0.0000,-0.0000,0.0000,-0.0000
sensor_6,0.0000,-0.0000,-0.0000,-0.0000,0.0000,0.0000,-0.0000,-0.0000,-0.0000,0.0000,...,-0.0000,0.0000,0.0000,0.0000,-0.0000,0.0000,0.0000,-0.0000,0.0000,-0.0000
sensor_7,-1.1924,-30.2096,-0.0000,-0.0000,0.0000,0.0000,-0.2586,-2.9940,-5.2608,-0.0000,...,-0.0407,0.3224,-0.0207,-0.0000,-0.7958,0.0000,0.0000,0.0982,0.0586,33.9853
sensor_8,0.1027,1.9310,-0.0000,-0.0000,0.0000,0.0000,0.0197,0.2189,0.3992,0.0000,...,0.0035,-0.2233,0.0016,0.0000,0.0583,0.0000,0.0000,-0.0074,-0.0044,-2.3072
sensor_9,-3.7599,354.7717,-0.0001,-0.0000,0.0000,0.0000,0.9092,14.2346,17.8336,-0.0000,...,-0.1231,131.0891,0.0751,-0.0000,3.8039,0.0000,0.0000,-0.3540,-0.2148,-302.6434
sensor_10,0.0000,-0.0000,-0.0000,-0.0000,0.0000,0.0000,-0.0000,-0.0000,-0.0000,0.0000,...,-0.0000,0.0000,0.0000,0.0000,-0.0000,0.0000,0.0000,-0.0000,0.0000,-0.0000
sensor_11,0.3394,9.6263,0.0000,-0.0000,0.0000,0.0000,0.0814,0.9301,1.6391,0.0000,...,0.0124,0.0054,0.0064,0.0000,0.2464,0.0000,0.0000,-0.0307,-0.0183,-10.7610
sensor_12,-0.9903,-25.7474,-0.0000,0.0000,0.0000,0.0000,-0.2226,-2.5379,-4.4956,-0.0000,...,-0.0349,0.3713,-0.0176,-0.0000,-0.6715,0.0000,0.0000,0.0834,0.0500,28.9167
sensor_13,0.1086,1.9429,0.0000,-0.0000,0.0000,0.0000,0.0198,0.2194,0.3998,-0.0000,...,0.0044,-0.2245,0.0016,-0.0000,0.0585,0.0000,0.0000,-0.0074,-0.0045,-2.3171
sensor_14,-8.4912,247.1554,-0.0002,-0.0000,0.0000,0.0000,0.1703,5.5751,2.8248,0.0000,...,-0.2245,132.7387,0.0154,0.0000,1.4774,0.0000,0.0000,-0.0757,-0.0434,-189.7342
sensor_15,0.0415,1.2544,0.0000,0.0000,0.0000,0.0000,0.0105,0.1200,0.2109,0.0000,...,0.0016,0.0154,0.0012,0.0000,0.0322,0.0000,0.0000,-0.0039,-0.0023,-1.3933
sensor_16,0.0000,-0.0000,-0.0000,-0.0000,0.0000,0.0000,-0.0000,-0.0000,-0.0000,0.0000,...,-0.0000,0.0000,0.0000,0.0000,-0.0000,0.0000,0.0000,-0.0000,0.0000,-0.0000
sensor_17,1.5028,50.2675,0.0000,0.0000,0.0000,0.0000,0.4029,4.6578,8.1129,-0.0000,...,0.0585,1.4774,0.0322,-0.0000,2.1303,0.0000,0.0000,-0.1510,-0.0907,-54.7139
sensor_18,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
sensor_19,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
sensor_20,-0.2061,-6.0215,-0.0000,-0.0000,0.0000,0.0000,-0.0496,-0.5670,-1.0053,-0.0000,...,-0.0074,-0.0757,-0.0039,-0.0000,-0.1510,0.0000,0.0000,0.0286,0.0111,6.6070
sensor_21,-0.1071,-3.5920,-0.0000,0.0000,0.0000,0.0000,-0.0297,-0.3413,-0.5952,0.0000,...,-0.0045,-0.0434,-0.0023,0.0000,-0.0907,0.0000,0.0000,0.0111,0.0102,3.9692
RUL,79.9170,-3155.1332,-0.0006,-0.0000,0.0000,0.0000,-17.6097,-206.5406,-355.0099,-0.0000,...,-2.3171,-189.7342,-1.3933,-0.0000,-54.7139,0.0000,0.0000,6.6070,3.9692,4493.9132

In [19]:
### Homo

In [20]:
# ===============================
# 4. Features & Target
# ===============================
x = data[['unit_number', 'time_in_cycles', 'OS1', 'OS2', 'OS3',
          'sensor_1','sensor_2','sensor_3','sensor_4','sensor_5',
          'sensor_6','sensor_7','sensor_8','sensor_9','sensor_10',
          'sensor_11','sensor_12','sensor_13','sensor_14','sensor_15',
          'sensor_16','sensor_17','sensor_18','sensor_19','sensor_20',
          'sensor_21']]

y = data['RUL']

In [21]:
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from statsmodels.stats.diagnostic import het_breuschpagan

# Add constant
X_const = sm.add_constant(x)

# Fit OLS model
model = sm.OLS(y, X_const).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    RUL   R-squared:                       0.639
Model:                            OLS   Adj. R-squared:                  0.639
Method:                 Least Squares   F-statistic:                     3318.
Date:                Mon, 22 Dec 2025   Prob (F-statistic):               0.00
Time:                        15:58:05   Log-Likelihood:            -1.7249e+05
No. Observations:               33727   AIC:                         3.450e+05
Df Residuals:                   33708   BIC:                         3.452e+05
Df Model:                          18
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
unit_number        0.2001      0.008     26.251      0.000       0.185       0.215
time_in_cycles    -0.4264      0.005    -84.433      0.000      -0.436      -0.417
OS1              -79.6836    100.584     -0.792      0.428    -276.832     117.465
OS2             -108.2428    747.565     -0.145      0.885   -1573.496    1357.010
OS3                3.9007      0.360     10.837      0.000       3.195       4.606
sensor_1          20.2318      1.867     10.837      0.000      16.572      23.891
sensor_2          -4.5613      0.720     -6.333      0.000      -5.973      -3.150
sensor_3          -0.2355      0.054     -4.343      0.000      -0.342      -0.129
sensor_4          -0.4605      0.053     -8.721      0.000      -0.564      -0.357
sensor_5           0.5703      0.053     10.837      0.000       0.467       0.673
sensor_6           0.8429      0.078     10.837      0.000       0.690       0.995
sensor_7           4.0394      0.524      7.716      0.000       3.013       5.065
sensor_8         -47.3244      6.892     -6.866      0.000     -60.834     -33.815
sensor_9          -0.4425      0.044     -9.950      0.000      -0.530      -0.355
sensor_10          0.0507      0.005     10.837      0.000       0.042       0.060
sensor_11        -22.3821      2.041    -10.964      0.000     -26.383     -18.381
sensor_12          6.0073      0.690      8.703      0.000       4.654       7.360
sensor_13        -47.8529      6.856     -6.980      0.000     -61.291     -34.415
sensor_14         -0.3204      0.049     -6.516      0.000      -0.417      -0.224
sensor_15        -59.2251     10.764     -5.502      0.000     -80.323     -38.127
sensor_16          0.0012      0.000     10.837      0.000       0.001       0.001
sensor_17         -0.7375      0.227     -3.247      0.001      -1.183      -0.292
sensor_18         93.1487      8.596     10.837      0.000      76.301     109.996
sensor_19          3.9007      0.360     10.837      0.000       3.195       4.606
sensor_20          7.9084      2.145      3.687      0.000       3.704      12.113
sensor_21         19.3474      3.602      5.371      0.000      12.287      26.408
==============================================================================
Omnibus:                     3102.450   Durbin-Watson:                   0.052
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4138.966
Skew:                           0.778   Prob(JB):                         0.00
Kurtosis:                       3.724   Cond. No.                     1.15e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.39e-20. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [22]:
# ===============================
# 5. Train-Test Split
# ===============================
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.30, random_state=0)

In [23]:
# ===============================
# 6. Baseline Linear Regression
# ===============================
lr = LinearRegression()
lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)
print("Linear Regression R2:", r2_score(y_test, y_pred))

Linear Regression R2: 0.6405480114021604

In [24]:
# ===============================
# 7. Multiple Models Comparison
# ===============================
models = [
    ("Linear", LinearRegression()),
    ("Ridge", Ridge()),
    ("Lasso", Lasso()),
    ("SVR", SVR()),
    ("Decision Tree", DecisionTreeRegressor()),
    ("Random Forest", RandomForestRegressor()),
    ("KNN", KNeighborsRegressor()),
    ('gbr' , GradientBoostingRegressor()),
    ('xgb' , XGBRegressor()),
    ("lgbm" , LGBMRegressor())]  


for name, model in models:
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(f"{name}  :", r2_score(y_test, y_pred))

Linear  : 0.6405480114021604
Ridge  : 0.6405087463178596
Lasso  : 0.6297029710395277
SVR  : 0.020573922043817916
Decision Tree  : 0.6810701264451767
Random Forest  : 0.8338557191934147
KNN  : 0.7254687878152715
gbr  : 0.7718672770177086
xgb  : 0.9088543007422613
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001753 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3080
[LightGBM] [Info] Number of data points in the train set: 23608, number of used features: 18
[LightGBM] [Info] Start training from score 120.827749
lgbm  : 0.8923700332591487

In [70]:
# ===============================
# 8. Feature Selection (SelectKBest)
# ===============================
kbest = SelectKBest(score_func=f_regression, k=25)
X_kbest = kbest.fit_transform(x, y)


selected_features = x.columns[kbest.get_support()]
print("Selected Features:", selected_features)

Selected Features: Index(['unit_number', 'time_in_cycles', 'OS1', 'OS2', 'sensor_1', 'sensor_2',
       'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8',
       'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13',
       'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18',
       'sensor_19', 'sensor_20', 'sensor_21'],
      dtype='object')

C:\Users\anand\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:381: RuntimeWarning: invalid value encountered in sqrt
  X_norms = np.sqrt(row_norms(X.T, squared=True) - n_samples * X_means**2)

In [71]:
# ===============================
# 9. Split + Scaling Function
# ===============================
def split_scalar(indep_X, dep_Y):
    X_train, X_test, y_train, y_test = train_test_split(
        indep_X, dep_Y, test_size=0.25, random_state=0
    )
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test  = sc.transform(X_test)
    return X_train, X_test, y_train, y_test

In [72]:
# ===============================
# 10. R2 Prediction Function
# ===============================
def r2_prediction(model, X_test, y_test):
    y_pred = model.predict(X_test)
    return r2_score(y_test, y_pred)

In [73]:
# ===============================
# 11. Model Functions
# ===============================
def Linear_Model(X_train, y_train, X_test, y_test):
    model = LinearRegression()
    model.fit(X_train, y_train)
    return r2_prediction(model, X_test, y_test)

def SVM_Linear(X_train, y_train, X_test, y_test):
    model = SVR(kernel='linear')
    model.fit(X_train, y_train)
    return r2_prediction(model, X_test, y_test)

def SVM_RBF(X_train, y_train, X_test, y_test):
    model = SVR(kernel='rbf')
    model.fit(X_train, y_train)
    return r2_prediction(model, X_test, y_test)

def Decision_Model(X_train, y_train, X_test, y_test):
    model = DecisionTreeRegressor(random_state=0)
    model.fit(X_train, y_train)
    return r2_prediction(model, X_test, y_test)

def Random_Model(X_train, y_train, X_test, y_test):
    model = RandomForestRegressor(n_estimators=100, random_state=0)
    model.fit(X_train, y_train)
    return r2_prediction(model, X_test, y_test)

In [74]:
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score

# ===============================
# Wrapper functions for regressors
# ===============================
def GBR_Model(X_train, y_train, X_test, y_test):
    model = GradientBoostingRegressor()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    return r2_score(y_test, y_pred)

def XGB_Model(X_train, y_train, X_test, y_test):
    model = XGBRegressor()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    return r2_score(y_test, y_pred)

def LGBM_Model(X_train, y_train, X_test, y_test):
    model = LGBMRegressor()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    return r2_score(y_test, y_pred)

# ===============================
# Apply Models on KBest Features
# ===============================
X_train_k, X_test_k, y_train_k, y_test_k = split_scalar(X_kbest, y)

results = {
    "Linear": Linear_Model(X_train_k, y_train_k, X_test_k, y_test_k),
    "SVM Linear": SVM_Linear(X_train_k, y_train_k, X_test_k, y_test_k),
    "SVM RBF": SVM_RBF(X_train_k, y_train_k, X_test_k, y_test_k),
    "Decision Tree": Decision_Model(X_train_k, y_train_k, X_test_k, y_test_k),
    "Random Forest": Random_Model(X_train_k, y_train_k, X_test_k, y_test_k),
    "GBR": GBR_Model(X_train_k, y_train_k, X_test_k, y_test_k),
    "XGB": XGB_Model(X_train_k, y_train_k, X_test_k, y_test_k),
    "LGBM": LGBM_Model(X_train_k, y_train_k, X_test_k, y_test_k)
}

# ===============================
# Display Results
# ===============================
result_df = pd.DataFrame(results, index=["R2 Score"])

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002551 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3084
[LightGBM] [Info] Number of data points in the train set: 25295, number of used features: 18
[LightGBM] [Info] Start training from score 120.640403

C:\Users\anand\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [47]:
result_df # 10

,Linear,SVM Linear,SVM RBF,Decision Tree,Random Forest,GBR,XGB,LGBM
R2 Score,0.6227,0.6090,0.6477,0.3067,0.6586,0.6674,0.6452,0.6666

In [57]:
result_df # 15

,Linear,SVM Linear,SVM RBF,Decision Tree,Random Forest,GBR,XGB,LGBM
R2 Score,0.6340,0.6208,0.6687,0.3707,0.6877,0.6903,0.6719,0.6926

In [67]:
result_df # 20

,Linear,SVM Linear,SVM RBF,Decision Tree,Random Forest,GBR,XGB,LGBM
R2 Score,0.6407,0.6269,0.6743,0.6700,0.8388,0.7703,0.9113,0.8923

In [75]:
result_df #25

,Linear,SVM Linear,SVM RBF,Decision Tree,Random Forest,GBR,XGB,LGBM
R2 Score,0.6407,0.6269,0.6743,0.6694,0.8390,0.7703,0.9113,0.8923

In [ ]:
from sklearn.model_selection import GridSearchCV

models = {
    "LR": (LinearRegression(), {}),
    "Ridge": (Ridge(), {'alpha':[1]}),
    "Lasso": (Lasso(), {'alpha':[1]}),
    
    "SVR": (SVR(), {"kernel": ["rbf", "linear"],
    "C": [0.1, 1, 10, 100],
    "epsilon": [0.01, 0.1, 0.2],
    "gamma": ["scale", "auto"]}),
    
    "DT": (DecisionTreeRegressor(), {"max_depth": [None, 3, 5, 10, 20],
    "min_samples_split": [2, 5, 10, 20],
    "min_samples_leaf": [1, 5, 10, 20],
    "max_features": [None, "sqrt", "log2"]}),
    
    "RF": (RandomForestRegressor(), {"n_estimators": [100, 200, 300],
    "max_depth": [None, 5, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 5, 10],
    "max_features": ["sqrt", "log2", None]}),
    
    "KNN": (KNeighborsRegressor(), {"n_neighbors": [3, 5, 7, 9, 15, 25],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan", "minkowski"]}),
    
    "GBR": (GradientBoostingRegressor(), {"learning_rate": [0.01, 0.05, 0.1, 0.2],
    "n_estimators": [100, 200, 300],
    "max_depth": [2, 3, 4, 5],
    "subsample": [0.6, 0.8, 1.0],
    "min_samples_leaf": [1, 5, 10],
    "criterion": ["friedman_mse", "squared_error"]}),
    
    "XGB": (XGBRegressor(objective='reg:squarederror'), {"learning_rate": [0.01, 0.05, 0.1, 0.2],
    "n_estimators": [100, 200, 300],
    "max_depth": [3, 4, 5, 6],
    "subsample": [0.6, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.8, 1.0],
    "min_child_weight": [1, 3, 5],
    "gamma": [0, 0.1, 0.3]}),
    
    "LGBM": (LGBMRegressor(), {"learning_rate": [0.01, 0.05, 0.1],
    "n_estimators": [100, 200, 300],
    "num_leaves": [15, 31, 63],
    "max_depth": [-1, 5, 10],
    "subsample": [0.6, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.8, 1.0],
    "min_child_samples": [5, 10, 20]})
}

for name,(m,p) in models.items():
    gs = GridSearchCV(m, p, cv=3)
    gs.fit(x_train, y_train)
    print(name, gs.best_score_)